### ISSUE TITLE
Review of First Commit of README.md

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Community#1]
@maaku @tuurdemeester @waynevaughan

I wanted to have something to point to at end of today's twitter [thread](https://twitter.com/ChristopherA/status/993511329146191872), so I have posted a first pass at a document describing #BlockchainCommons, and I have mentioned your names and your background. Could you review it and confirm here if it is ok or if changes are required? Thanks!

**Comment by shannona** [comment]
Closing out old issues. We've gone a few iterations beyond this.
