### ISSUE TITLE
PROJECT: Integrate a New C Library into LBTCftCL

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/Community#140]
The `libbitcoinrpc` RPC C library used in Learning Bitcoin from the Command Line has become outdated as discussed here:
https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/issues/561

It's not just that it's old, it's that it no longer compiles correctly without intervention.

So, we need a new C library. Tasks would be:

- [ ] Find a new C library for sending RPC commands to bitcoind
- [ ] Document its setup and basic usage in [16.1](https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/16_1_Accessing_Bitcoind_with_C.md#161-accessing-bitcoind-in-c-with-rpc-libraries)
- [ ] Rewrite [16.2](https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/16_1_Accessing_Bitcoind_with_C.md#161-accessing-bitcoind-in-c-with-rpc-libraries) to use the new C library
- [ ] Check chapter 17 to see if there is any use of the old library, and if so update it.

As far as I know the `curl` library and the `jansson` library remain OK. Therefore, I expect much of the commentary, as well as the code not directly using the old library, can still be used.

**Comment by shannona** [comment]
Here's an alternative path for this task: bring the existing library up to date.

- [ ] Incorporate existing PR from old repo https://github.com/gitmarek/libbitcoinrpc/pull/1
- [ ] Figure out why it doesn't compile per LBTCftCL per https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/16_1_Accessing_Bitcoind_with_C.md#set-up-libbitcoinrpc
- [ ] Fix that
- [ ] Go through RPC commands and update any others that have fallen out of date.

I'm agnostic as to whether to follow the original task list (replacing it) or this one (updating it). I think a lot of it depends on whether there's a great alternative RPC Bitcoin library for C; when I originally decided to use this a few years ago, there was not.

**Comment by shannona** [comment]
Debian 11 is our default OS that we expect people to be using when they're running Learning Bitcoin, so that's where we should be testing. If you need a Debian 11 linode setup, just let me know.

**Comment by shikharvashistha** [comment]
Created a pull including the fix and changelog for the commit https://github.com/gitmarek/libbitcoinrpc/pull/2

**Comment by shannona** [comment]
Resolved this by repairing old version & having our own copy of it in a repo.
