### ISSUE TITLE
PROJECT: Silicon Salon 2

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/Community#144]
Issue tracking tasks associated with Silicon Salon event: 

* [x] Seed discussions, kick off plans for event.
* [x] initial sponsors approval (Bunnie Studies, Crossbar, Proxy, Foundation Devices)
* [x] identify blackout dates & choose draft date
   * Blackout: September 20-October 4
   * Draft Date: September 14
* [x] draft of invite to send for additional sponsors (see below)
* [x] shared with additional potential sponsors 
  * [x] list of potential sponsors
* [x] Feedback on date and final invite
  * [x] confirm final date with Sponsors. (September 14)
* [x] Setup web page & eventbrite
* [x] Send invites
* [x] Plan presentations
  * [x] @ChristopherA intro & @kanzure's bookend
  * [x] Review other presentations, suggest content
    * [x] Crossbar
    * [x] Proxy
    * [x] Foundation Devices
    * [x] Bunnie Studios
    * [x] VLS
* [x] Edit presentations for time
* [x] Finalize Agenda
* [x] Email registrants Monday before.
* [x] Event 
  * [x] Recording & Bryan’s notes to
* [x] Post Event
  * [x] Reorganize Website to support multiple events
  * [x] Publish initial results to website (https://www.SiliconSalon.info)
     * [x] Presentation Slideshows
     * [x] Presentation Videos
     * [x] Presentation Transcripts
     * [x] Key Quotes
     * [ ] Key Slides
  * [x] Seed new topic discussion on Github (Reused existing Secure Boot/Firmware/Supply Chain)
  * [x] Write Tweetstorm
  * [x] Post Tweetstorm
  * [x] Email via Eventbrite to all participants 
  * [x] Post to Airgap Discussion / Silicon Salon that everything is posted (and correction can be made via Issues or PRs)
* [ ] Debrief/Post-mortem with Sustaining & Project Patrons
    * [ ] Crossbar
    * [ ] Proxy
    * [ ] Bunnie Studios
    * [ ] Foundation Devices
* [x] Promote final website and presentations.

/cc @kanzure @shannona

**Comment by kanzure** [comment]
One of these should be a hackathon.

**Comment by kanzure** [comment]
Why is this closed?

**Comment by ChristopherA** [comment]
Wasn’t intended to be closed, the silicon salon 1 was to be closed.
