### ISSUE TITLE
Updating #SmartCustody website

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Community#16]
We have a separate static web site for our #SmartCustody project, as its audience & patrons are a bit different than the broader Blockchain Commons audience & patrons.

* Website: https://www.SmartCustody.com
* Github Repo: https://github.com/BlockchainCommons/www.SmartCustody.com

We are currently leveraging the native GitHub static website features of [Jekyll](https://jekyllrb.com) [remote](https://github.blog/2017-11-29-use-any-theme-with-github-pages/) which means that simply by committing the changes to the repo, the website is updated.

We are using one of the more sophisticated Jekyll themes called [HydeJack Pro](https://hydejack.com), however, it almost but doesn't quite work perfectly with `remote-theme` and in general requires some relatively sophisticated knowledge of Jekyll's various templating tools (significantly more complex than the default themes used by Github which are quite easy to understand).  After paying for the license to HydeJack Pro the author refunded our payment when we asked for help with `remote-theme` and other advanced Jekyll features. 

Thus we are in a situation with a difficult to configure and sometimes problematical static website and theme, and we are not able to get support and updates from the theme author.

In the long run we probably should change theme to one we can self-support, but in the meantime, here is a list of some updates that we need to do, and some our problems.

* [ ] Add new blog post about seeking sponsor for update of book.
* [ ] We need to add link to sponsors.md to sidebar #ThemeProblem
* [ ] We need to link sponsors.md elsewhere
* [ ] We need to add book download links to project pages
* [ ] Investigate if there are some other ways to update the theme #ThemeProblem

**Comment by cprkrn** [comment]
Is there any strong arguments against using the ones suggested by Github? Personally, I like [Architect](https://pages-themes.github.io/architect/), both PDFs would fit nicely on the sidebar.

**Comment by ChristopherA** [comment]
The default themes from Github in general are fairly limiting, and there are some much better remote-theme capable themes.

**Comment by shannona** [comment]
I think this needs to be rescoped, as we've somewhat replaced the #SC site with our new projects page, and likely need to rebuild the #SC site as something more book-focused. So, let's open a new issue or add some TODO items when we decide what we want to do there.
