### ISSUE TITLE
BTCPay: Use new descriptor account for 2023

### ISSUE THREAD

**Issue by nochiel** [BlockchainCommons/Community#169]
- [x] Close out old descriptor/account on 12/31/22
- [x] Create a new descriptor (page? just update?) for BTCPay for 1/1/23

**Comment by shannona** [comment]
Remind @ChristopherA to get you a new descriptor, so that we can have this live for 1/1/23.

**Comment by nochiel** [comment]
> Remind @ChristopherA to get you a new descriptor, so that we can have this live for 1/1/23.

@ChristopherA Is it sufficient to simply increment the `account number` portion of the descriptor? 

Because Sparrow now (at least for me) doesn't display separate "accounts" as separate wallets, we need to be sure it still allows us to filter transactions (including change addresses) by account identifier. 

Does that sound reasonable?

**Comment by ChristopherA** [comment]
I think I’d like to create a whole new seed, and shard a SSKR 2:3 share with copy to Shannon & partner. I’d do multisig but would want to test more.

**Comment by nochiel** [comment]
> I think I’d like to create a whole new seed, and shard a SSKR 2:3 share with copy to Shannon & partner. I’d do multisig but would want to test more.

Okay. That makes sense. Feel free to ping me when you're ready.

**Comment by nochiel** [comment]
The new descriptor is active and exports of the previous wallet were sent to @ChristopherA.
