### ISSUE TITLE
Fall 2020 Cohort of Internship Program

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Community#17]
Post here if you have questions or are interested in participating in the fall 2020 cohort of the @BlockchainCommons 2nd cohort of our virtual internship program. Email [me](mailto:ChristopherA@LifeWithAlacrity.com) your CV, some highlights of some of the things you like to work on, and what you’d like to get out of an internship with Us. Also what platforms you develop on, and what kind of smart phone and development environment you use.

We also welcome applications outside of the developer community, as not all projects are code. In particular, we are seeking library science students to help us organize our links, references and work, education specialists to work on tutorials, and pre-law students to help with our advocacy in the creation of new laws in places like Wyoming where our advice has been well respected and is turning into law.

At whatever level of development skill you do have (or not) we do hope that you'll at least have worked through the first chapters of the https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line course and have gotten to as far as you can, or that have tried out the Gordian Wallet TestFlight beta https://github.com/BlockchainCommons/GordianWallet-iOS even if you don't have development skills. Command line isn't easy, but it isn't hard either!

interns can expect to participate in a private Signal chats with fellow interns and members of the @BlockchainCommons community, as well as weekly open "intern office hours" video chats with open questioins and sometimes guests from the industry. In addition, each intern is offered 3 personal "mentorship" calls with @ChristopherA to discuss their education and career plans for the future.

We do offer a small honorarium in bitcoin over the course of the program as interns meet 3 milestones. If you agree to participate in our internship program we'll need you to work with you on a work order to describe the your project you'll be leading, and you'll need GPG sign our [internship agreement](https://github.com/BlockchainCommons/Open-Development/tree/master/internship-contract) and any CLAs our projects use for contribution assignments. 

Deadlines for the October through November internship program is September 28th and starts October 5th through  December 18th. When your 3 internship milestones are complete we can offer you a certification of completion.

If you can't participate in this fall's program, we will likely offer one on the spring and summer of 2021.

We look forward to collaborating with you!

-- Christopher Allen

**Comment by kouloumos** [comment]
I am really interested in participating in the fall 2020 cohort. **I am super excited actually!**

**Comment by ChristopherA** [comment]
@kouloumos wrote: 
> I am really interested in participating in the fall 2020 cohort. **I am super excited actually!**

Send me your CV to ChristopherA@LifeWithAlacrity.com, and highlights from it of some of the things you like to work on (backend code, UX, hardware, cryptographic research, privacy, standards, decentralized identity, open source community development, digital assets or privacy law, etc.) and some specifics of what you’d like to get out of an internship with Blockchain Commons. Also what platforms you write or develop on, and what kind of smart phone you use.

Thanks!

— Christopher Allen

**Comment by prayank23** [comment]
I am interested, will send my CV today.

**Comment by ChristopherA** [comment]
These are some of the questions that I have asked as followups to potential interns that have send me CVs so far. If you answer then in your cover letter, it can save a latency cycle ;-)

(Also note that these questions are more focused toward developers, but I'm hoping to get some interns in law, library science, and education as well, and they likely would have different followup questions).

* What is your primary development environment and what hardware do you run it on? What kind of smartphone do you use and which version of Android or iOS?

* As a software developer, what languages and tools do your LIKE, vs ones you know and can use.

* A key part of being successful as an intern is picking and scoping a new feature in an existing open source project or a new small project to be the lead on that is relevant to Blockchain Commons and our advocacy that can be completed in three months (in this case by the end of the year). You'll collaborate with the other interns with their projects, but there should be one where you are the lead. Given that, any early thoughts on what kinds of existing projects that Blockchain Commons is doing you might want to add a feature to? Or some small new project that fits into our advocacy?

* You clearly care about and have some advocacy around bitcoin, blockchain, and related technologies, but what aspect of it drives you to do so?

* Software developers are whole people, and just coding machines. What professional skills and talents do you bring to the table that are not about code?

* What specifically would you like to learn or get out of a 3-month internship with Blockchain Commons? What appealed to you that you are applying for an internship with us?

-- Christopher Allen
