### ISSUE TITLE
WIP: Backup GitHub Metadata

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/Community#174]
Another community project issue, maybe something to post to bc-community signal, is that we need to evaluate backing up metadata (issues, pr details, discussions, etc.) from Github. 

There are two scripts that I know do it https://github.com/clockfort/GitHub-Backup & https://github.com/josegonzalez/python-github-backup but there is also a $20 a month service. https://rewind.com/products/backups/github/

lead: @nochiel (investigate)

---

- [ ] Test josegonzalez/python-github-backup
  - [x] Create a Personal Access Token for the BlockchainCommons org.
  - [x] Checkpoint backup for 2022 (https://github.com/BlockchainCommons/Community/issues/174#issuecomment-1362283945).
  - [x] Verify back up of [metadata](https://docs.github.com/en/rest/overview/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#metadata)
    - How much of this metadata do we actually need?
- [x] Schedule backups on `bc-monitor` using `systemd timers`
- [x] Document setup and configuration.
  - The Access Token should be renewed/expired annually.

**Comment by shannona** [comment]
We'd ideally like to do this when the year changes on 12/31 if possible, @nochiel

**Comment by nochiel** [comment]
> We'd ideally like to do this when the year changes on 12/31 if possible, @nochiel

Understood. I'll look into this today and test if I can use the scripts to back up to bc-monitoring. If it works, I'll set up a Cron job.

**Comment by nochiel** [comment]
The backups are now running weekly on `bc-monitor`. 
The deployment script and documentation is in https://github.com/BlockchainCommons/deployment-scripts/tree/master/github-backup.
