### ISSUE TITLE
Document roadmap for Spotbit

### ISSUE THREAD

**Issue by watersnake1** [BlockchainCommons/Community#22]
# Todo
- [x] Make Q2 and Summer Virtual Internship plan for features to be added:
- [x] Document which issues have already been solved by the 2022 refactor.

# A summary of changes made in the 2022 refactor:
- See https://github.com/BlockchainCommons/spotbit/pull/55 for details on the refactor.
- Spotbit no longer stores an offline database. Instead, we prefer to fetch data from exchange APIs on demand. This fixes https://github.com/BlockchainCommons/spotbit/issues/41 and https://github.com/BlockchainCommons/spotbit/issues/16.
- Use of FastAPI instead of Flask allowed us to be more flexible in 
  - refactoring and automatically documenting the API.
    -  https://github.com/BlockchainCommons/spotbit/issues/51
  - improving uptime/reliablity.  
  - improving perfomance using FastAPI's async-first features.
    - Ref. https://flask.palletsprojects.com/en/2.2.x/async-await/#when-to-use-quart-instead

---

Previously, @watersnake1 wrote:

> I am preparing to back off from the lead developer of spotbit role - I am now back to school full-time and managing another internship, so this isn't really something that I can maintain any longer. Spotbit itself is a functioning system for managing current data, both from a database and directly from exchanges, and for providing averaged price info based on sets of 5 exchanges. 

> The next phase of Spotbit is naturally historical data. The first challenge in this process is backfilling gaps in the database that can be caused by downtime. I've detailed that in an issue here https://github.com/BlockchainCommons/spotbit/issues/41

> There is also some great js code written by Javier that needs to be moved to a clearnet website: https://github.com/BlockchainCommons/spotbit/issues/40

> And finally, recently there have been responsiveness issues with the server. I suspect its a tor issue, as I have seen it happen in other onion services I run: https://github.com/BlockchainCommons/spotbit/issues/39
@Fonta1n3 I am convinced its not an optimization issue, but perhaps an issue with how tor is set up.

> My next priority is to migrate the linode server to control of Blockchain Commons, which I will complete tomorrow.

> @ChristopherA thank you very much for this internship opportunity this summer. It has been a truly great experience working with everyone at blockchain commons these last few months!

**Comment by shannona** [comment]
Thank you for a terrific project, @watersnake1 . Closing this out, as spotbit has the individual issues that need to be followed. We should be sure to consider issues on individual repos when looking into future projects (as well as closed issues here).

**Comment by ChristopherA** [comment]
Reopening. We don't really have a formal lead for Spotbit, though @nochiel has been serving that role with the current refactor. We also have some interest from summer 2022 interns in contributing to the next generation of Spotbit, but we don't have a good roadmap.

@Nociel, your thoughts?

**Comment by ChristopherA** [comment]
It would also be very useful for the spotbit team doing any front-end changes, to give feedback on how to skin our esplora server and other services in similar ways, for both public web at http://esplora.blockchaincommons.com and via tor under different javascript scenarios.

See issue #142

**Comment by ChristopherA** [comment]
FEATURE REQUEST: I'd really like Spotbit instances to be able to connect via a torgap to a bitcoin-core instance or Esplora for fee estimation. This needs scoping and a separate concrete community project issue.

**Comment by ChristopherA** [comment]
@nochiel we need a plan.

**Comment by nochiel** [comment]
@ChristopherA I've added a Spotbit roadmap here: https://github.com/BlockchainCommons/spotbit/edit/master/README.md#roadmap-1 

It servers as a starting point that can be discussed/improved by posting issues/feedback in the BlockchainCommons/Spotbit repository.
