### ISSUE TITLE
Updating to new Blockchain Commons Apple Certificate, expiring in a few days

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Community#29]
Our Apple Developer certificate for Blockchain Common's is expiring in a few days.

As we have a number of new TestFlight versions coming out now, we probably should to go ahead an convert over to the new one now. There are a number of us building with it (@ChristopherA @Fonta1n3 @wolfmcnally @shannona) so we should coordinate the switch over on the Gordian Core Test Team on Signal.

--- 
Your Distribution Certificate will no longer be valid in 30 days. To generate a new certificate, sign in and visit Certificates, Identifiers & Profiles.

Certificate: Distribution
Team ID: YZHG975W3A

To learn more about expired certificates, visit the certificates support page.

Best regards,
Apple Developer Program Support
---

**Comment by wolfmcnally** [comment]
I think this should be resolved now.

**Comment by ChristopherA** [comment]
@Fonta1n3 I was getting a notice that your developer certificate needed to be renewed? If you did, could you close this issue?

**Comment by shannona** [comment]
This is no longer an issue.
