### ISSUE TITLE
Integrate cooperation vs competition thoughts

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Community#3]
I'm finding I'm having to tell some potential collaborations something along of the lines of

>We don't want to be a hardware company or a consumer wallet company. Our goal is to support blockchain ecosystem with research, best practices, reference code and implementations, etc. We want to coordinate these into helping the whole community.

We need to integrate this into how we say what we do.

cc/ @shannona @vinaytaylor

**Comment by shannona** [comment]
We've gone a few iterations beyond this in our messaging, so I'm closing this out.
