### ISSUE TITLE
Need App Stores (Apple, Google) strategy for version numbers, release status, alpha beta rc, etc.

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Community#35]
Need a proposal from @wolfmcnally

**Comment by wolfmcnally** [comment]
Here's what I know about Apple version numbers.

- [Technical Note TN2420: Version Numbers and Build Numbers](https://developer.apple.com/library/archive/technotes/tn2420/_index.html)
- [CFBundleVersion](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102364)
- [CFBundleShortVersionString](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-111349)
- [Forum: Version Number](https://developer.apple.com/forums/thread/50931)
- [Forum: Why Apple Rejects My Version Number](https://developer.apple.com/forums/thread/109765)

Here is the Android guidelines:
- [Version your app](https://developer.android.com/studio/publish/versioning)

The thing I see in common is that Apple and Google both have a private version field that is *not* shown to users, and a public version field that *is*. In Google's case, it is required to be an increasing integer. In Apple's case, the same requirement is true for macOS, but for iOS it can be a dotted version number as long as it only *increases*. The least common denominator among the three is as I have recommended: Use the public-facing version string for the actual name of the upcoming release (starting at "1.0") and identify every release including internal ones using an increasing integer in the non-user-facing field. The public-facing field should *not* have exactly the same semantics as "semantic versioning," as this is more appropriate for developer-facing libraries; rather, it should be so users can identify bug-fix releases, minor improvement releases, and major improvement releases.

**Comment by wolfmcnally** [comment]
One of the nice things about using a monotonically-increasing integer for release number is that it is amenable to automated release processes. And even though it is not shown to the public, it *can* be revealed to testers. In the case of Apple's Test Flight, it automatically is revealed to testers.

**Comment by ChristopherA** [comment]
@Fonta1n3 @wolfmcnally 

Are we now being consistent here for Guardian, UR Vault and Gordian Cosigner?

**Comment by ChristopherA** [comment]
@shannona is this now done to our satisfaction? Is it linked in appropriate places? If yes, link them here and let's close this issue.

**Comment by shannona** [comment]
I've added a link to our Community README, which has this sort of info.
https://github.com/BlockchainCommons/Community/blob/master/README.md
