### ISSUE TITLE
Modt big issue for blockchain

### ISSUE THREAD

**Issue by imansayadi3** [BlockchainCommons/Community#69]
Big and funny problem in blockchain .. If the user forgets the password or lost phones, his 12 words are only good for grazing the cottonwool. Go back 15 years ago and think about the password hit... The creators of Windows had bigger and more up-to-date brains.
40% of the people who create wallets and become members of the blockchain network do not even have access to information about txid . If people want very strong security, make them stronger than ...bip 39 and. more and more.password hit is The most important option and firs And the most essential..Maybe someone became dumb. And maybe someone had their hands amputated and more importantly maybe someone got Alzheimer's disease. You do not have the right to tell anyone not to forget your password for bust all your money, otherwise you can update your think and your option with a password hit.. Or do not react and give additional explanations. But this will make fun of the network and reduce the power of the network to reach the peak ..or stay in that

۰

**Comment by shannona** [comment]
This is a topic we regularly approach in Smart Custody and is covered for example in #127, but also in the specifics of our #SmartCustody scenarios, most recently:
https://github.com/BlockchainCommons/SmartCustody/blob/master/Docs/Scenario-Multisig.md
