### ISSUE TITLE
2020 Summer Internship Project: Adapt Bitcoin Standup Script for Windows

### ISSUE THREAD

**Issue by chiselinc** [BlockchainCommons/Community#9]
I'm volunteering to take lead on adapting the Linux scripts for Bitcoin Standup into a single script which allows for standalone installation on Windows. 

Per discussion with Christopher, the current process on windows requires the user to install developer tools manually, setup Homebrew, and then download the script from Blockchain Commons.

We'd like to enable a easier/less technical workflow to reduce the technical barriers to running a node for Windows users.

The rough requirements are:
* Install tools for Bitcoin Core
* Set it up so it runs through Tor
* Set up some way for user to see QR code/corresponding info to connect devices to their node
* Put wrappers around it for simple UI

@ChristopherA this is my understanding from notes on our call, please clarify or add anything I'm missing at this early stage!

**Comment by chiselinc** [comment]
I don't appear to have sufficient write access for this repo to apply labels, but I had intended to set this as "intern project" and "status: scoping" 😸

**Comment by ChristopherA** [comment]
I've added you.

**Comment by ChristopherA** [comment]
I think I'd probably divide it a little different. See if this helps.

* Scope requirements
  * Scripting environment: What are people using when installing the Windows version of Bitcoin-Core?What development scripting tools are Windows-based bitcoin developers preferring to use? I know that there are multiple choices here.
  * Pick a scripting environment that can help automate the install of Bitcoin-Core and Tor settings.
  * Research any configuration best practices for Windows users of Bitcoin-Core and Tor. There may be some settings that are not default that we should recommend.
* Basics
  * Automate install of Bitcoin-Core with our settings.
  * Automate install of Tor with our settings.
* Sweet extras
  * Initially get user input from terminal, but investigate if there are ways to present simple dialogues to user to make choices during setup. 
  * What else can we do to make it super easy.
* Test
  * Test again, then Regression Test ;-)
* Document, release, and publicize to the world!

-- Christopher Allen

**Comment by shannona** [comment]
Closing out summer 2020 issues.
